apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops-web
  ports:
    - protocol: TCP
      port: 80       # Port the service listens on
      targetPort: 3000 # Port inside the container
  type: LoadBalancer